### ISSUE TITLE
TypeError and application crashed after adding ng-hint (1.3.2)

### ISSUE THREAD

**Issue by Sand22** [angular/angular-hint#53]
Hi, I installed angular-hint and added ng-hint directive next to ng-app as mentioned in instruction. I received some hints, but also get the following errors and my app crashed:

```
TypeError: Object function (elem) {
        elem = angular.element(elem);
        for(var i = 0; i < elem.length; i+=2){
          if(elem[i].getElementsByTagName){
            var toSend = Array.prototype.slice.call(elem[i].getElementsByTagName('*'));
    ...<omitted>... } has no method '$$addBindingClass'
    at Object.ngBindCompile [as compile] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:21605:16)
    at applyDirectivesToNode (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:7367:32)
    at compileNodes (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6915:15)
    at compile (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6822:15)
    at applyDirectivesToNode (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:7280:33)
    at compileNodes (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6915:15)
    at compileNodes (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6927:15)
    at compile (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6822:15)
    at applyDirectivesToNode (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:7280:33)
    at compileNodes (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6915:15) <span ng-if="$last" ng-bind="breadcrumb.label">
```

```
TypeError: object is not a function
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:7608:13
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:347:20)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:7607:11)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6993:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6996:13)
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:6872:30)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:1456:27
    at Scope.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:14200:28)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:14298:23)
    at bootstrapApply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.js:1454:15)
```

**Comment by jfrumar** [comment]
Same problem on 1.4.0-rc.1

**Comment by SomeKittens** [comment]
Which version (i.e. git sha) were you using?
